# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lib/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 750)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lib\\mDirt.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffa02f;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #404040;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
"}\n"
"\n"
"QWidget:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton #a, #buttonAddBlock, #buttonGeneratePack, #buttonRemoveBlock, #buttonEditBlock, #buttonEditItem, #buttonRemoveItem, #itemAddButton, #buttonRemoveRecipe, #buttonEditRecipe, #buttonAddRecipe\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"QPushButton #a, #slot0, #slot1, #slot2, #slot3, #slot4, #slot5, #slot6, #slot7, #slot8, #slot9 {\n"
"background-color: rgba(255, 255, 255, 0)\n"
"}\n"
"\n"
"QLabel #a, #topFace, #leftFace, #backFace, #rightFace, #bottomFace, #frontFace, #itemTextureLabel, #slot0, #slot1, #slot2, #slot3, #slot4, #slot5, #slot6, #slot7, #slot8, #slot9\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color :QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-text-color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    text -color: black; \n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"     text -color: black; \n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:/down_arrow.png);\n"
"}\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/images/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-style: solid;\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(:/images/checkbox.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setEnabled(False)
        self.status.setGeometry(QtCore.QRect(600, 420, 281, 20))
        self.status.setText("")
        self.status.setObjectName("status")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 921, 721))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.author = QtWidgets.QLineEdit(self.tab)
        self.author.setGeometry(QtCore.QRect(350, 220, 121, 20))
        self.author.setObjectName("author")
        self.packName = QtWidgets.QLineEdit(self.tab)
        self.packName.setGeometry(QtCore.QRect(350, 130, 113, 20))
        self.packName.setObjectName("packName")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(290, 90, 221, 16))
        self.label_15.setObjectName("label_15")
        self.packVersion = QtWidgets.QComboBox(self.tab)
        self.packVersion.setGeometry(QtCore.QRect(350, 250, 69, 22))
        self.packVersion.setObjectName("packVersion")
        self.packVersion.addItem("")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(300, 160, 61, 16))
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(300, 130, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(300, 280, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(300, 70, 281, 16))
        self.label_14.setObjectName("label_14")
        self.packNamespace = QtWidgets.QLineEdit(self.tab)
        self.packNamespace.setGeometry(QtCore.QRect(370, 160, 113, 20))
        self.packNamespace.setInputMethodHints(QtCore.Qt.ImhNone)
        self.packNamespace.setObjectName("packNamespace")
        self.packDescription = QtWidgets.QLineEdit(self.tab)
        self.packDescription.setGeometry(QtCore.QRect(370, 190, 181, 20))
        self.packDescription.setObjectName("packDescription")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(300, 250, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(300, 220, 47, 13))
        self.label_7.setObjectName("label_7")
        self.vmdPrefix = QtWidgets.QLineEdit(self.tab)
        self.vmdPrefix.setGeometry(QtCore.QRect(370, 280, 41, 20))
        self.vmdPrefix.setMaxLength(428)
        self.vmdPrefix.setObjectName("vmdPrefix")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(300, 190, 61, 16))
        self.label_12.setObjectName("label_12")
        self.buttonGeneratePack = QtWidgets.QPushButton(self.tab)
        self.buttonGeneratePack.setGeometry(QtCore.QRect(380, 330, 91, 23))
        self.buttonGeneratePack.setObjectName("buttonGeneratePack")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.placeSound = QtWidgets.QLineEdit(self.tab_2)
        self.placeSound.setGeometry(QtCore.QRect(120, 160, 151, 20))
        self.placeSound.setObjectName("placeSound")
        self.blockName = QtWidgets.QLineEdit(self.tab_2)
        self.blockName.setGeometry(QtCore.QRect(90, 70, 181, 20))
        self.blockName.setInputMethodHints(QtCore.Qt.ImhNone)
        self.blockName.setObjectName("blockName")
        self.blockModel = QtWidgets.QComboBox(self.tab_2)
        self.blockModel.setEnabled(True)
        self.blockModel.setGeometry(QtCore.QRect(380, 70, 69, 22))
        self.blockModel.setObjectName("blockModel")
        self.blockModel.addItem("")
        self.blockModel.addItem("")
        self.bottomFaceBtn = QtWidgets.QPushButton(self.tab_2)
        self.bottomFaceBtn.setEnabled(True)
        self.bottomFaceBtn.setGeometry(QtCore.QRect(380, 240, 41, 41))
        self.bottomFaceBtn.setAutoFillBackground(False)
        self.bottomFaceBtn.setText("")
        self.bottomFaceBtn.setCheckable(False)
        self.bottomFaceBtn.setFlat(True)
        self.bottomFaceBtn.setObjectName("bottomFaceBtn")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(40, 40, 71, 16))
        self.label_5.setObjectName("label_5")
        self.bottomFace = QtWidgets.QLabel(self.tab_2)
        self.bottomFace.setEnabled(True)
        self.bottomFace.setGeometry(QtCore.QRect(380, 240, 41, 41))
        self.bottomFace.setText("")
        self.bottomFace.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.bottomFace.setObjectName("bottomFace")
        self.blockDisplayName = QtWidgets.QLineEdit(self.tab_2)
        self.blockDisplayName.setGeometry(QtCore.QRect(130, 40, 141, 20))
        self.blockDisplayName.setObjectName("blockDisplayName")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 71, 16))
        self.label_3.setObjectName("label_3")
        self.blockDrop = QtWidgets.QLineEdit(self.tab_2)
        self.blockDrop.setGeometry(QtCore.QRect(90, 130, 181, 20))
        self.blockDrop.setObjectName("blockDrop")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 47, 13))
        self.label_2.setObjectName("label_2")
        self.blockTextureLabel = QtWidgets.QLabel(self.tab_2)
        self.blockTextureLabel.setEnabled(True)
        self.blockTextureLabel.setGeometry(QtCore.QRect(380, 110, 47, 13))
        self.blockTextureLabel.setObjectName("blockTextureLabel")
        self.topFace = QtWidgets.QLabel(self.tab_2)
        self.topFace.setEnabled(True)
        self.topFace.setGeometry(QtCore.QRect(380, 140, 41, 41))
        self.topFace.setText("")
        self.topFace.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.topFace.setObjectName("topFace")
        self.backFace = QtWidgets.QLabel(self.tab_2)
        self.backFace.setEnabled(True)
        self.backFace.setGeometry(QtCore.QRect(380, 190, 41, 41))
        self.backFace.setText("")
        self.backFace.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.backFace.setObjectName("backFace")
        self.directionalCheck = QtWidgets.QCheckBox(self.tab_2)
        self.directionalCheck.setGeometry(QtCore.QRect(30, 190, 81, 17))
        self.directionalCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.directionalCheck.setObjectName("directionalCheck")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(40, 70, 47, 13))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(40, 100, 61, 16))
        self.label_6.setObjectName("label_6")
        self.frontFace = QtWidgets.QLabel(self.tab_2)
        self.frontFace.setEnabled(True)
        self.frontFace.setGeometry(QtCore.QRect(480, 190, 41, 41))
        self.frontFace.setText("")
        self.frontFace.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.frontFace.setObjectName("frontFace")
        self.buttonAddBlock = QtWidgets.QPushButton(self.tab_2)
        self.buttonAddBlock.setGeometry(QtCore.QRect(90, 230, 75, 23))
        self.buttonAddBlock.setObjectName("buttonAddBlock")
        self.leftFace = QtWidgets.QLabel(self.tab_2)
        self.leftFace.setEnabled(True)
        self.leftFace.setGeometry(QtCore.QRect(330, 190, 41, 41))
        self.leftFace.setText("")
        self.leftFace.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.leftFace.setObjectName("leftFace")
        self.blockModelLabel = QtWidgets.QLabel(self.tab_2)
        self.blockModelLabel.setEnabled(True)
        self.blockModelLabel.setGeometry(QtCore.QRect(330, 70, 47, 13))
        self.blockModelLabel.setObjectName("blockModelLabel")
        self.leftFaceBtn = QtWidgets.QPushButton(self.tab_2)
        self.leftFaceBtn.setEnabled(True)
        self.leftFaceBtn.setGeometry(QtCore.QRect(330, 190, 41, 41))
        self.leftFaceBtn.setAutoFillBackground(False)
        self.leftFaceBtn.setText("")
        self.leftFaceBtn.setCheckable(False)
        self.leftFaceBtn.setFlat(True)
        self.leftFaceBtn.setObjectName("leftFaceBtn")
        self.blockBase = QtWidgets.QLineEdit(self.tab_2)
        self.blockBase.setGeometry(QtCore.QRect(110, 100, 161, 20))
        self.blockBase.setText("")
        self.blockBase.setObjectName("blockBase")
        self.rightFaceBtn = QtWidgets.QPushButton(self.tab_2)
        self.rightFaceBtn.setEnabled(True)
        self.rightFaceBtn.setGeometry(QtCore.QRect(430, 190, 41, 41))
        self.rightFaceBtn.setAutoFillBackground(False)
        self.rightFaceBtn.setText("")
        self.rightFaceBtn.setCheckable(False)
        self.rightFaceBtn.setFlat(True)
        self.rightFaceBtn.setObjectName("rightFaceBtn")
        self.frontFaceBtn = QtWidgets.QPushButton(self.tab_2)
        self.frontFaceBtn.setEnabled(True)
        self.frontFaceBtn.setGeometry(QtCore.QRect(480, 190, 41, 41))
        self.frontFaceBtn.setAutoFillBackground(False)
        self.frontFaceBtn.setText("")
        self.frontFaceBtn.setCheckable(False)
        self.frontFaceBtn.setFlat(True)
        self.frontFaceBtn.setObjectName("frontFaceBtn")
        self.backFaceBtn = QtWidgets.QPushButton(self.tab_2)
        self.backFaceBtn.setEnabled(True)
        self.backFaceBtn.setGeometry(QtCore.QRect(380, 190, 41, 41))
        self.backFaceBtn.setAutoFillBackground(False)
        self.backFaceBtn.setText("")
        self.backFaceBtn.setCheckable(False)
        self.backFaceBtn.setFlat(True)
        self.backFaceBtn.setObjectName("backFaceBtn")
        self.rightFace = QtWidgets.QLabel(self.tab_2)
        self.rightFace.setEnabled(True)
        self.rightFace.setGeometry(QtCore.QRect(430, 190, 41, 41))
        self.rightFace.setText("")
        self.rightFace.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.rightFace.setObjectName("rightFace")
        self.topFaceBtn = QtWidgets.QPushButton(self.tab_2)
        self.topFaceBtn.setEnabled(True)
        self.topFaceBtn.setGeometry(QtCore.QRect(380, 140, 41, 41))
        self.topFaceBtn.setAutoFillBackground(False)
        self.topFaceBtn.setText("")
        self.topFaceBtn.setCheckable(False)
        self.topFaceBtn.setFlat(True)
        self.topFaceBtn.setObjectName("topFaceBtn")
        self.buttonEditBlock = QtWidgets.QPushButton(self.tab_2)
        self.buttonEditBlock.setGeometry(QtCore.QRect(770, 280, 75, 23))
        self.buttonEditBlock.setObjectName("buttonEditBlock")
        self.blockList = QtWidgets.QListWidget(self.tab_2)
        self.blockList.setGeometry(QtCore.QRect(594, 80, 256, 192))
        self.blockList.setObjectName("blockList")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(694, 60, 47, 13))
        self.label_9.setObjectName("label_9")
        self.buttonRemoveBlock = QtWidgets.QPushButton(self.tab_2)
        self.buttonRemoveBlock.setGeometry(QtCore.QRect(594, 280, 75, 23))
        self.buttonRemoveBlock.setObjectName("buttonRemoveBlock")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(380, 281, 141, 81))
        self.groupBox.setObjectName("groupBox")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 20, 121, 51))
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.placeSound.raise_()
        self.blockName.raise_()
        self.blockModel.raise_()
        self.label_5.raise_()
        self.bottomFace.raise_()
        self.blockDisplayName.raise_()
        self.label_3.raise_()
        self.blockDrop.raise_()
        self.label_2.raise_()
        self.blockTextureLabel.raise_()
        self.topFace.raise_()
        self.backFace.raise_()
        self.directionalCheck.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.frontFace.raise_()
        self.buttonAddBlock.raise_()
        self.leftFace.raise_()
        self.blockModelLabel.raise_()
        self.leftFaceBtn.raise_()
        self.blockBase.raise_()
        self.frontFaceBtn.raise_()
        self.backFaceBtn.raise_()
        self.rightFace.raise_()
        self.topFaceBtn.raise_()
        self.buttonEditBlock.raise_()
        self.blockList.raise_()
        self.label_9.raise_()
        self.buttonRemoveBlock.raise_()
        self.rightFaceBtn.raise_()
        self.bottomFaceBtn.raise_()
        self.groupBox.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.itemList = QtWidgets.QListWidget(self.tab_3)
        self.itemList.setGeometry(QtCore.QRect(640, 70, 256, 192))
        self.itemList.setObjectName("itemList")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(740, 50, 47, 13))
        self.label_16.setObjectName("label_16")
        self.buttonEditItem = QtWidgets.QPushButton(self.tab_3)
        self.buttonEditItem.setGeometry(QtCore.QRect(816, 270, 75, 23))
        self.buttonEditItem.setObjectName("buttonEditItem")
        self.buttonRemoveItem = QtWidgets.QPushButton(self.tab_3)
        self.buttonRemoveItem.setGeometry(QtCore.QRect(640, 270, 75, 23))
        self.buttonRemoveItem.setObjectName("buttonRemoveItem")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(40, 40, 71, 16))
        self.label_8.setObjectName("label_8")
        self.itemDisplayName = QtWidgets.QLineEdit(self.tab_3)
        self.itemDisplayName.setGeometry(QtCore.QRect(120, 40, 113, 20))
        self.itemDisplayName.setObjectName("itemDisplayName")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(40, 70, 47, 13))
        self.label_17.setObjectName("label_17")
        self.itemName = QtWidgets.QLineEdit(self.tab_3)
        self.itemName.setGeometry(QtCore.QRect(80, 70, 151, 20))
        self.itemName.setObjectName("itemName")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(40, 100, 51, 16))
        self.label_18.setObjectName("label_18")
        self.itemBase = QtWidgets.QLineEdit(self.tab_3)
        self.itemBase.setGeometry(QtCore.QRect(100, 100, 131, 20))
        self.itemBase.setObjectName("itemBase")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(260, 40, 47, 13))
        self.label_19.setObjectName("label_19")
        self.itemTextureLabel = QtWidgets.QLabel(self.tab_3)
        self.itemTextureLabel.setGeometry(QtCore.QRect(310, 28, 41, 41))
        self.itemTextureLabel.setText("")
        self.itemTextureLabel.setObjectName("itemTextureLabel")
        self.itemTextureButton = QtWidgets.QPushButton(self.tab_3)
        self.itemTextureButton.setGeometry(QtCore.QRect(310, 28, 41, 41))
        self.itemTextureButton.setText("")
        self.itemTextureButton.setFlat(True)
        self.itemTextureButton.setObjectName("itemTextureButton")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(40, 140, 71, 16))
        self.label_20.setObjectName("label_20")
        self.itemComponents = QtWidgets.QTextEdit(self.tab_3)
        self.itemComponents.setEnabled(False)
        self.itemComponents.setGeometry(QtCore.QRect(110, 140, 351, 251))
        self.itemComponents.setObjectName("itemComponents")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(260, 90, 31, 16))
        self.label_21.setObjectName("label_21")
        self.itemModel = QtWidgets.QComboBox(self.tab_3)
        self.itemModel.setGeometry(QtCore.QRect(300, 90, 91, 22))
        self.itemModel.setObjectName("itemModel")
        self.itemModel.addItem("")
        self.itemModel.addItem("")
        self.itemModel.addItem("")
        self.itemAddButton = QtWidgets.QPushButton(self.tab_3)
        self.itemAddButton.setGeometry(QtCore.QRect(230, 440, 75, 23))
        self.itemAddButton.setObjectName("itemAddButton")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.recipeList = QtWidgets.QListWidget(self.tab_4)
        self.recipeList.setGeometry(QtCore.QRect(630, 80, 256, 192))
        self.recipeList.setObjectName("recipeList")
        self.buttonEditRecipe = QtWidgets.QPushButton(self.tab_4)
        self.buttonEditRecipe.setGeometry(QtCore.QRect(806, 280, 75, 23))
        self.buttonEditRecipe.setObjectName("buttonEditRecipe")
        self.buttonRemoveRecipe = QtWidgets.QPushButton(self.tab_4)
        self.buttonRemoveRecipe.setGeometry(QtCore.QRect(630, 280, 75, 23))
        self.buttonRemoveRecipe.setObjectName("buttonRemoveRecipe")
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(730, 60, 61, 16))
        self.label_23.setObjectName("label_23")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 40, 481, 391))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.shapeless = QtWidgets.QCheckBox(self.tab_5)
        self.shapeless.setGeometry(QtCore.QRect(40, 210, 81, 17))
        self.shapeless.setObjectName("shapeless")
        self.slot0Label = QtWidgets.QLabel(self.tab_5)
        self.slot0Label.setEnabled(True)
        self.slot0Label.setGeometry(QtCore.QRect(40, 20, 41, 41))
        self.slot0Label.setText("")
        self.slot0Label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.slot0Label.setObjectName("slot0Label")
        self.slot6Label = QtWidgets.QLabel(self.tab_5)
        self.slot6Label.setEnabled(True)
        self.slot6Label.setGeometry(QtCore.QRect(140, 20, 41, 41))
        self.slot6Label.setText("")
        self.slot6Label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.slot6Label.setObjectName("slot6Label")
        self.slot6 = QtWidgets.QPushButton(self.tab_5)
        self.slot6.setEnabled(True)
        self.slot6.setGeometry(QtCore.QRect(140, 20, 41, 41))
        self.slot6.setAutoFillBackground(False)
        self.slot6.setText("")
        self.slot6.setCheckable(False)
        self.slot6.setFlat(True)
        self.slot6.setObjectName("slot6")
        self.slot9Label = QtWidgets.QLabel(self.tab_5)
        self.slot9Label.setEnabled(True)
        self.slot9Label.setGeometry(QtCore.QRect(240, 70, 41, 41))
        self.slot9Label.setText("")
        self.slot9Label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.slot9Label.setObjectName("slot9Label")
        self.slot5 = QtWidgets.QPushButton(self.tab_5)
        self.slot5.setEnabled(True)
        self.slot5.setGeometry(QtCore.QRect(90, 120, 41, 41))
        self.slot5.setAutoFillBackground(False)
        self.slot5.setText("")
        self.slot5.setCheckable(False)
        self.slot5.setFlat(True)
        self.slot5.setObjectName("slot5")
        self.slot8 = QtWidgets.QPushButton(self.tab_5)
        self.slot8.setEnabled(True)
        self.slot8.setGeometry(QtCore.QRect(140, 120, 41, 41))
        self.slot8.setAutoFillBackground(False)
        self.slot8.setText("")
        self.slot8.setCheckable(False)
        self.slot8.setFlat(False)
        self.slot8.setObjectName("slot8")
        self.slot2 = QtWidgets.QPushButton(self.tab_5)
        self.slot2.setEnabled(True)
        self.slot2.setGeometry(QtCore.QRect(40, 120, 41, 41))
        self.slot2.setAutoFillBackground(False)
        self.slot2.setText("")
        self.slot2.setCheckable(False)
        self.slot2.setFlat(True)
        self.slot2.setObjectName("slot2")
        self.slot9 = QtWidgets.QPushButton(self.tab_5)
        self.slot9.setEnabled(True)
        self.slot9.setGeometry(QtCore.QRect(240, 70, 41, 41))
        self.slot9.setAutoFillBackground(False)
        self.slot9.setText("")
        self.slot9.setCheckable(False)
        self.slot9.setAutoExclusive(False)
        self.slot9.setFlat(True)
        self.slot9.setObjectName("slot9")
        self.slot4 = QtWidgets.QPushButton(self.tab_5)
        self.slot4.setEnabled(True)
        self.slot4.setGeometry(QtCore.QRect(90, 70, 41, 41))
        self.slot4.setAutoFillBackground(False)
        self.slot4.setText("")
        self.slot4.setCheckable(False)
        self.slot4.setFlat(True)
        self.slot4.setObjectName("slot4")
        self.slot1 = QtWidgets.QPushButton(self.tab_5)
        self.slot1.setEnabled(True)
        self.slot1.setGeometry(QtCore.QRect(40, 70, 41, 41))
        self.slot1.setAutoFillBackground(False)
        self.slot1.setText("")
        self.slot1.setCheckable(False)
        self.slot1.setFlat(True)
        self.slot1.setObjectName("slot1")
        self.exact = QtWidgets.QCheckBox(self.tab_5)
        self.exact.setGeometry(QtCore.QRect(40, 180, 131, 17))
        self.exact.setObjectName("exact")
        self.slot3Label = QtWidgets.QLabel(self.tab_5)
        self.slot3Label.setEnabled(True)
        self.slot3Label.setGeometry(QtCore.QRect(90, 20, 41, 41))
        self.slot3Label.setText("")
        self.slot3Label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.slot3Label.setObjectName("slot3Label")
        self.slot7 = QtWidgets.QPushButton(self.tab_5)
        self.slot7.setEnabled(True)
        self.slot7.setGeometry(QtCore.QRect(140, 70, 41, 41))
        self.slot7.setAutoFillBackground(False)
        self.slot7.setText("")
        self.slot7.setCheckable(False)
        self.slot7.setFlat(True)
        self.slot7.setObjectName("slot7")
        self.slot1Label = QtWidgets.QLabel(self.tab_5)
        self.slot1Label.setEnabled(True)
        self.slot1Label.setGeometry(QtCore.QRect(40, 70, 41, 41))
        self.slot1Label.setText("")
        self.slot1Label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.slot1Label.setObjectName("slot1Label")
        self.slot7Label = QtWidgets.QLabel(self.tab_5)
        self.slot7Label.setEnabled(True)
        self.slot7Label.setGeometry(QtCore.QRect(140, 70, 41, 41))
        self.slot7Label.setText("")
        self.slot7Label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.slot7Label.setObjectName("slot7Label")
        self.slot8Label = QtWidgets.QLabel(self.tab_5)
        self.slot8Label.setEnabled(True)
        self.slot8Label.setGeometry(QtCore.QRect(140, 120, 41, 41))
        self.slot8Label.setText("")
        self.slot8Label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.slot8Label.setObjectName("slot8Label")
        self.slot3 = QtWidgets.QPushButton(self.tab_5)
        self.slot3.setEnabled(True)
        self.slot3.setGeometry(QtCore.QRect(90, 20, 41, 41))
        self.slot3.setAutoFillBackground(False)
        self.slot3.setText("")
        self.slot3.setCheckable(False)
        self.slot3.setFlat(True)
        self.slot3.setObjectName("slot3")
        self.slot2Label = QtWidgets.QLabel(self.tab_5)
        self.slot2Label.setEnabled(True)
        self.slot2Label.setGeometry(QtCore.QRect(40, 120, 41, 41))
        self.slot2Label.setText("")
        self.slot2Label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.slot2Label.setObjectName("slot2Label")
        self.slot5Label = QtWidgets.QLabel(self.tab_5)
        self.slot5Label.setEnabled(True)
        self.slot5Label.setGeometry(QtCore.QRect(90, 120, 41, 41))
        self.slot5Label.setText("")
        self.slot5Label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.slot5Label.setObjectName("slot5Label")
        self.slot0 = QtWidgets.QPushButton(self.tab_5)
        self.slot0.setEnabled(True)
        self.slot0.setGeometry(QtCore.QRect(40, 20, 41, 41))
        self.slot0.setAutoFillBackground(False)
        self.slot0.setStyleSheet("")
        self.slot0.setText("")
        self.slot0.setCheckable(False)
        self.slot0.setFlat(True)
        self.slot0.setObjectName("slot0")
        self.slot4Label = QtWidgets.QLabel(self.tab_5)
        self.slot4Label.setEnabled(True)
        self.slot4Label.setGeometry(QtCore.QRect(90, 70, 41, 41))
        self.slot4Label.setText("")
        self.slot4Label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.slot4Label.setObjectName("slot4Label")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit.setGeometry(QtCore.QRect(110, 260, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_25 = QtWidgets.QLabel(self.tab_5)
        self.label_25.setGeometry(QtCore.QRect(40, 260, 71, 16))
        self.label_25.setObjectName("label_25")
        self.slot9Count = QtWidgets.QSpinBox(self.tab_5)
        self.slot9Count.setGeometry(QtCore.QRect(240, 120, 42, 22))
        self.slot9Count.setMinimum(1)
        self.slot9Count.setMaximum(64)
        self.slot9Count.setObjectName("slot9Count")
        self.shapeless.raise_()
        self.slot0Label.raise_()
        self.slot6Label.raise_()
        self.slot9Label.raise_()
        self.exact.raise_()
        self.slot3Label.raise_()
        self.slot1Label.raise_()
        self.slot7Label.raise_()
        self.slot8Label.raise_()
        self.slot2Label.raise_()
        self.slot5Label.raise_()
        self.slot4Label.raise_()
        self.slot1.raise_()
        self.slot3.raise_()
        self.slot2.raise_()
        self.slot5.raise_()
        self.slot6.raise_()
        self.slot4.raise_()
        self.slot0.raise_()
        self.slot8.raise_()
        self.slot7.raise_()
        self.slot9.raise_()
        self.lineEdit.raise_()
        self.label_25.raise_()
        self.slot9Count.raise_()
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_24 = QtWidgets.QLabel(self.tab_6)
        self.label_24.setGeometry(QtCore.QRect(150, 110, 81, 41))
        self.label_24.setObjectName("label_24")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.buttonAddRecipe = QtWidgets.QPushButton(self.tab_4)
        self.buttonAddRecipe.setGeometry(QtCore.QRect(420, 450, 75, 23))
        self.buttonAddRecipe.setObjectName("buttonAddRecipe")
        self.tabWidget.addTab(self.tab_4, "")
        self.tabWidget.raise_()
        self.status.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 923, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionImport_from_mrdt = QtWidgets.QAction(MainWindow)
        self.actionImport_from_mrdt.setObjectName("actionImport_from_mrdt")
        self.actiont = QtWidgets.QAction(MainWindow)
        self.actiont.setObjectName("actiont")
        self.actionExport_to_mrdt_2 = QtWidgets.QAction(MainWindow)
        self.actionExport_to_mrdt_2.setObjectName("actionExport_to_mrdt_2")
        self.menuFile.addAction(self.actionImport_from_mrdt)
        self.menuFile.addAction(self.actionExport_to_mrdt_2)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "mDirt - A Datapack Tool for custom blocks"))
        self.author.setToolTip(_translate("MainWindow", "<html><head/><body><p>The author of the pack. This is used occasionally in the datapack, and should only be lowercase characters, nothing else.</p></body></html>"))
        self.author.setPlaceholderText(_translate("MainWindow", "jupiterdev"))
        self.packName.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Name of the Datapack &amp; Resource Pack.<br/>Supports A-Z, a-z, spaces, _, -, !.</p></body></html>"))
        self.packName.setPlaceholderText(_translate("MainWindow", "The Ruby Pack"))
        self.label_15.setText(_translate("MainWindow", "Made by Jupiter Dev & JustJoshinDev 2024"))
        self.packVersion.setToolTip(_translate("MainWindow", "<html><head/><body><p>The version the pack will be made for.</p></body></html>"))
        self.packVersion.setItemText(0, _translate("MainWindow", "1.21.3"))
        self.label_11.setText(_translate("MainWindow", "Namespace:"))
        self.label_10.setText(_translate("MainWindow", "Name:"))
        self.label_4.setText(_translate("MainWindow", "CMD Prefix:"))
        self.label_14.setText(_translate("MainWindow", "mDirt - A Datapack Tool for custom blocks"))
        self.packNamespace.setToolTip(_translate("MainWindow", "<html><head/><body><p>The namespace. Only supports lowercase letters &amp; underscores.</p></body></html>"))
        self.packNamespace.setPlaceholderText(_translate("MainWindow", "ores"))
        self.packDescription.setToolTip(_translate("MainWindow", "The Description! Almost all characters are supported."))
        self.packDescription.setPlaceholderText(_translate("MainWindow", "Adds new ores to Minecraft!"))
        self.label_13.setText(_translate("MainWindow", "Version:"))
        self.label_7.setText(_translate("MainWindow", "Author:"))
        self.vmdPrefix.setToolTip(_translate("MainWindow", "<html><head/><body><p>The prefix for all custom model data in the pack. For instance, if you choose 428, the first block would be 4280001, then 4280002, etc.</p></body></html>"))
        self.vmdPrefix.setPlaceholderText(_translate("MainWindow", "428"))
        self.label_12.setText(_translate("MainWindow", "Description:"))
        self.buttonGeneratePack.setToolTip(_translate("MainWindow", "<html><head/><body><p>Generate the Pack(s)!<br/>Press only when you are done!</p></body></html>"))
        self.buttonGeneratePack.setText(_translate("MainWindow", "Generate Pack"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Datapack Details"))
        self.placeSound.setToolTip(_translate("MainWindow", "<html><head/><body><p>The sound your block should play when it is placed.<br/>Currently only supports default minecraft sounds,</p><p>but support for custom sounds is coming soon<span style=\" vertical-align:super;\">TM</span></p></body></html>"))
        self.placeSound.setPlaceholderText(_translate("MainWindow", "minecraft:block.stone.place"))
        self.blockName.setToolTip(_translate("MainWindow", "<html><head/><body><p>The name the program and the pack recognizes.<br/>Supports lowercase characters &amp; underscores.</p></body></html>"))
        self.blockName.setPlaceholderText(_translate("MainWindow", "ruby_ore"))
        self.blockModel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Block: A regular block.</p><p>Custom: Your own custom 3D model.</p></body></html>"))
        self.blockModel.setItemText(0, _translate("MainWindow", "Block"))
        self.blockModel.setItemText(1, _translate("MainWindow", "Custom"))
        self.bottomFaceBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Bottom face of the block</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Display Name:"))
        self.blockDisplayName.setToolTip(_translate("MainWindow", "<html><head/><body><p>The name the block will show in your inventory.</p></body></html>"))
        self.blockDisplayName.setPlaceholderText(_translate("MainWindow", "Ruby Ore"))
        self.label_3.setText(_translate("MainWindow", "Place Sound:"))
        self.blockDrop.setToolTip(_translate("MainWindow", "<html><head/><body><p>The item dropped when the block is broken.<br/>When empty, it will drop itself.</p></body></html>"))
        self.blockDrop.setPlaceholderText(_translate("MainWindow", "minecraft:diamond"))
        self.label_2.setText(_translate("MainWindow", "Drop:"))
        self.blockTextureLabel.setText(_translate("MainWindow", "Texture"))
        self.directionalCheck.setToolTip(_translate("MainWindow", "<html><head/><body><p>Should your block be directional?<br/>When checked, it will be placed like a log.<br/>Otherwise, it will always face up.</p></body></html>"))
        self.directionalCheck.setText(_translate("MainWindow", "Directional?"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_6.setText(_translate("MainWindow", "Base Block:"))
        self.buttonAddBlock.setToolTip(_translate("MainWindow", "<html><head/><body><p>Adds the block to the pack!</p></body></html>"))
        self.buttonAddBlock.setText(_translate("MainWindow", "Add Block"))
        self.blockModelLabel.setText(_translate("MainWindow", "Model:"))
        self.leftFaceBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Left face of the block</p></body></html>"))
        self.blockBase.setToolTip(_translate("MainWindow", "<html><head/><body><p>The base block. This will determine the mining speed, what kind of tool you</p><p>need to mine it, break/place/walking sounds, and more. Any minecraft block works here.</p></body></html>"))
        self.blockBase.setPlaceholderText(_translate("MainWindow", "minecraft:stone"))
        self.rightFaceBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Right face of the block</p></body></html>"))
        self.frontFaceBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Front face of the block</p></body></html>"))
        self.backFaceBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Back face of the block</p></body></html>"))
        self.topFaceBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Top face of the block</p></body></html>"))
        self.buttonEditBlock.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click a block from above, then press Edit to edit the block.</p></body></html>"))
        self.buttonEditBlock.setText(_translate("MainWindow", "Edit"))
        self.blockList.setToolTip(_translate("MainWindow", "<html><head/><body><p>A list of all custom blocks you have created.</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "All Blocks"))
        self.buttonRemoveBlock.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click a block from above, then press Remove to delete it.<br/>This action cannot be undone.</p></body></html>"))
        self.buttonRemoveBlock.setText(_translate("MainWindow", "Remove"))
        self.groupBox.setTitle(_translate("MainWindow", "Bottom"))
        self.label_22.setText(_translate("MainWindow", "If Model is set to custom, then only this texture will be applied to the whole model."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Blocks"))
        self.itemList.setToolTip(_translate("MainWindow", "<html><head/><body><p>A list of all custom items you have created.</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "All Items"))
        self.buttonEditItem.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click a items from above, then press Edit to edit the block.</p></body></html>"))
        self.buttonEditItem.setText(_translate("MainWindow", "Edit"))
        self.buttonRemoveItem.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click a items from above, then press Remove to delete it.<br/>This action cannot be undone.</p></body></html>"))
        self.buttonRemoveItem.setText(_translate("MainWindow", "Remove"))
        self.label_8.setText(_translate("MainWindow", "Display Name:"))
        self.itemDisplayName.setToolTip(_translate("MainWindow", "<html><head/><body><p>The name your item displays in your inventory.</p></body></html>"))
        self.itemDisplayName.setPlaceholderText(_translate("MainWindow", "Topaz"))
        self.label_17.setText(_translate("MainWindow", "Name:"))
        self.itemName.setToolTip(_translate("MainWindow", "<html><head/><body><p>The name the datapack recognizes your item as. Only supports lowercase and underscores.</p></body></html>"))
        self.itemName.setPlaceholderText(_translate("MainWindow", "topaz"))
        self.label_18.setText(_translate("MainWindow", "Base Item:"))
        self.itemBase.setToolTip(_translate("MainWindow", "<html><head/><body><p>The base item of your custom item.</p></body></html>"))
        self.itemBase.setPlaceholderText(_translate("MainWindow", "minecraft:iron_ingot"))
        self.label_19.setText(_translate("MainWindow", "Texture:"))
        self.itemTextureButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click to select your texture.</p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "Components:"))
        self.itemComponents.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">This feature is in development and is not enabled at the current time!</span></p><p>Any custom components you want to add to the item.</p></body></html>"))
        self.itemComponents.setPlaceholderText(_translate("MainWindow", "minecraft:custom_data={my_data:1b},attributes={[]}"))
        self.label_21.setText(_translate("MainWindow", "Model:"))
        self.itemModel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Generated for regular items.</p><p>Handheld for things such as swords or shovels.</p><p>Custom to select your own 3D model.</p></body></html>"))
        self.itemModel.setItemText(0, _translate("MainWindow", "Generated"))
        self.itemModel.setItemText(1, _translate("MainWindow", "Handheld"))
        self.itemModel.setItemText(2, _translate("MainWindow", "Custom"))
        self.itemAddButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Adds the item to be generated!</p></body></html>"))
        self.itemAddButton.setText(_translate("MainWindow", "Add Item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Items"))
        self.recipeList.setToolTip(_translate("MainWindow", "<html><head/><body><p>A list of all custom recipes you have created.</p></body></html>"))
        self.buttonEditRecipe.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click a recipe from above, then press Edit to edit the block.</p></body></html>"))
        self.buttonEditRecipe.setText(_translate("MainWindow", "Edit"))
        self.buttonRemoveRecipe.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click a recipe from above, then press Remove to delete it.<br/>This action cannot be undone.</p></body></html>"))
        self.buttonRemoveRecipe.setText(_translate("MainWindow", "Remove"))
        self.label_23.setText(_translate("MainWindow", "All Recipes"))
        self.shapeless.setToolTip(_translate("MainWindow", "<html><head/><body><p>Should the recipe be shapeless?</p></body></html>"))
        self.shapeless.setText(_translate("MainWindow", "Shapeless?"))
        self.slot6.setToolTip(_translate("MainWindow", "<html><head/><body><p>One of the 9 slots in a crafting table. Click to select item/block.</p></body></html>"))
        self.slot5.setToolTip(_translate("MainWindow", "<html><head/><body><p>One of the 9 slots in a crafting table. Click to select item/block.</p></body></html>"))
        self.slot8.setToolTip(_translate("MainWindow", "<html><head/><body><p>One of the 9 slots in a crafting table. Click to select item/block.</p></body></html>"))
        self.slot2.setToolTip(_translate("MainWindow", "<html><head/><body><p>One of the 9 slots in a crafting table. Click to select item/block.</p></body></html>"))
        self.slot9.setToolTip(_translate("MainWindow", "<html><head/><body><p>The output of the crafting recipe. Click to select.</p></body></html>"))
        self.slot4.setToolTip(_translate("MainWindow", "<html><head/><body><p>One of the 9 slots in a crafting table. Click to select item/block.</p></body></html>"))
        self.slot1.setToolTip(_translate("MainWindow", "<html><head/><body><p>One of the 9 slots in a crafting table. Click to select item/block.</p></body></html>"))
        self.exact.setToolTip(_translate("MainWindow", "<html><head/><body><p>Should it be exactly where places?</p></body></html>"))
        self.exact.setText(_translate("MainWindow", "Exactly where Placed?"))
        self.slot7.setToolTip(_translate("MainWindow", "<html><head/><body><p>One of the 9 slots in a crafting table. Click to select item/block.</p></body></html>"))
        self.slot3.setToolTip(_translate("MainWindow", "<html><head/><body><p>One of the 9 slots in a crafting table. Click to select item/block.</p></body></html>"))
        self.slot0.setToolTip(_translate("MainWindow", "<html><head/><body><p>One of the 9 slots in a crafting table. Click to select item/block.</p></body></html>"))
        self.lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>The name of the recipe! Should be lowercase &amp; underscores only.</p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "Recipe Name:"))
        self.slot9Count.setToolTip(_translate("MainWindow", "<html><head/><body><p>The count of the output.</p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Crafting"))
        self.label_24.setText(_translate("MainWindow", "COMING SOON!"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Smelting"))
        self.buttonAddRecipe.setToolTip(_translate("MainWindow", "<html><head/><body><p>Adds the recipe!</p></body></html>"))
        self.buttonAddRecipe.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Recipes"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionImport_from_mrdt.setText(_translate("MainWindow", "Import from .mrdt"))
        self.actiont.setText(_translate("MainWindow", "t"))
        self.actionExport_to_mrdt_2.setText(_translate("MainWindow", "Export to .mrdt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
