# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lib/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(926, 751)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lib\\mDirt.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffa02f;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #404040;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
"}\n"
"\n"
"QWidget:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton #a, #buttonAddBlock, #buttonGeneratePack, #buttonRemoveBlock, #buttonEditBlock\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QLabel #a, #topFace, #leftFace, #backFace, #rightFace, #bottomFace, #frontFace\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color :QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-text-color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    text -color: black; \n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"     text -color: black; \n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:/down_arrow.png);\n"
"}\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/images/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(:/images/checkbox.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 320, 47, 13))
        self.label.setObjectName("label")
        self.blockName = QtWidgets.QLineEdit(self.centralwidget)
        self.blockName.setGeometry(QtCore.QRect(70, 320, 181, 20))
        self.blockName.setInputMethodHints(QtCore.Qt.ImhNone)
        self.blockName.setObjectName("blockName")
        self.vmdPrefix = QtWidgets.QLineEdit(self.centralwidget)
        self.vmdPrefix.setGeometry(QtCore.QRect(340, 90, 41, 20))
        self.vmdPrefix.setMaxLength(428)
        self.vmdPrefix.setObjectName("vmdPrefix")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 90, 61, 16))
        self.label_4.setObjectName("label_4")
        self.blockDisplayName = QtWidgets.QLineEdit(self.centralwidget)
        self.blockDisplayName.setGeometry(QtCore.QRect(110, 290, 141, 20))
        self.blockDisplayName.setObjectName("blockDisplayName")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 290, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 350, 61, 16))
        self.label_6.setObjectName("label_6")
        self.blockBase = QtWidgets.QLineEdit(self.centralwidget)
        self.blockBase.setGeometry(QtCore.QRect(90, 350, 161, 20))
        self.blockBase.setText("")
        self.blockBase.setObjectName("blockBase")
        self.buttonAddBlock = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAddBlock.setGeometry(QtCore.QRect(80, 480, 75, 23))
        self.buttonAddBlock.setObjectName("buttonAddBlock")
        self.blockList = QtWidgets.QListWidget(self.centralwidget)
        self.blockList.setGeometry(QtCore.QRect(620, 50, 256, 192))
        self.blockList.setObjectName("blockList")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(540, -10, 21, 931))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(720, 30, 47, 13))
        self.label_9.setObjectName("label_9")
        self.buttonRemoveBlock = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRemoveBlock.setGeometry(QtCore.QRect(620, 250, 75, 23))
        self.buttonRemoveBlock.setObjectName("buttonRemoveBlock")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 250, 551, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 90, 47, 13))
        self.label_10.setObjectName("label_10")
        self.packName = QtWidgets.QLineEdit(self.centralwidget)
        self.packName.setGeometry(QtCore.QRect(80, 90, 113, 20))
        self.packName.setObjectName("packName")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 120, 61, 16))
        self.label_11.setObjectName("label_11")
        self.packNamespace = QtWidgets.QLineEdit(self.centralwidget)
        self.packNamespace.setGeometry(QtCore.QRect(100, 120, 113, 20))
        self.packNamespace.setInputMethodHints(QtCore.Qt.ImhNone)
        self.packNamespace.setObjectName("packNamespace")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(40, 150, 61, 16))
        self.label_12.setObjectName("label_12")
        self.packDescription = QtWidgets.QLineEdit(self.centralwidget)
        self.packDescription.setGeometry(QtCore.QRect(100, 150, 181, 20))
        self.packDescription.setObjectName("packDescription")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(40, 210, 47, 13))
        self.label_13.setObjectName("label_13")
        self.packVersion = QtWidgets.QComboBox(self.centralwidget)
        self.packVersion.setGeometry(QtCore.QRect(90, 210, 69, 22))
        self.packVersion.setObjectName("packVersion")
        self.packVersion.addItem("")
        self.buttonGeneratePack = QtWidgets.QPushButton(self.centralwidget)
        self.buttonGeneratePack.setGeometry(QtCore.QRect(700, 250, 91, 23))
        self.buttonGeneratePack.setObjectName("buttonGeneratePack")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(40, 30, 281, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(30, 50, 221, 16))
        self.label_15.setObjectName("label_15")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setEnabled(False)
        self.status.setGeometry(QtCore.QRect(600, 420, 281, 20))
        self.status.setText("")
        self.status.setObjectName("status")
        self.blockTextureLabel = QtWidgets.QLabel(self.centralwidget)
        self.blockTextureLabel.setEnabled(False)
        self.blockTextureLabel.setGeometry(QtCore.QRect(370, 360, 47, 13))
        self.blockTextureLabel.setObjectName("blockTextureLabel")
        self.blockResourceCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.blockResourceCheckBox.setGeometry(QtCore.QRect(320, 290, 141, 17))
        self.blockResourceCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.blockResourceCheckBox.setObjectName("blockResourceCheckBox")
        self.blockModelLabel = QtWidgets.QLabel(self.centralwidget)
        self.blockModelLabel.setEnabled(False)
        self.blockModelLabel.setGeometry(QtCore.QRect(320, 320, 47, 13))
        self.blockModelLabel.setObjectName("blockModelLabel")
        self.blockModel = QtWidgets.QComboBox(self.centralwidget)
        self.blockModel.setEnabled(False)
        self.blockModel.setGeometry(QtCore.QRect(370, 320, 69, 22))
        self.blockModel.setObjectName("blockModel")
        self.blockModel.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 380, 47, 13))
        self.label_2.setObjectName("label_2")
        self.blockDrop = QtWidgets.QLineEdit(self.centralwidget)
        self.blockDrop.setGeometry(QtCore.QRect(70, 380, 181, 20))
        self.blockDrop.setObjectName("blockDrop")
        self.topFace = QtWidgets.QLabel(self.centralwidget)
        self.topFace.setGeometry(QtCore.QRect(370, 390, 41, 41))
        self.topFace.setText("")
        self.topFace.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.topFace.setObjectName("topFace")
        self.rightFace = QtWidgets.QLabel(self.centralwidget)
        self.rightFace.setGeometry(QtCore.QRect(420, 440, 41, 41))
        self.rightFace.setText("")
        self.rightFace.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.rightFace.setObjectName("rightFace")
        self.bottomFace = QtWidgets.QLabel(self.centralwidget)
        self.bottomFace.setGeometry(QtCore.QRect(370, 490, 41, 41))
        self.bottomFace.setText("")
        self.bottomFace.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.bottomFace.setObjectName("bottomFace")
        self.leftFace = QtWidgets.QLabel(self.centralwidget)
        self.leftFace.setGeometry(QtCore.QRect(320, 440, 41, 41))
        self.leftFace.setText("")
        self.leftFace.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.leftFace.setObjectName("leftFace")
        self.backFace = QtWidgets.QLabel(self.centralwidget)
        self.backFace.setGeometry(QtCore.QRect(370, 440, 41, 41))
        self.backFace.setText("")
        self.backFace.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.backFace.setObjectName("backFace")
        self.frontFace = QtWidgets.QLabel(self.centralwidget)
        self.frontFace.setGeometry(QtCore.QRect(470, 440, 41, 41))
        self.frontFace.setText("")
        self.frontFace.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.frontFace.setObjectName("frontFace")
        self.topFaceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.topFaceBtn.setGeometry(QtCore.QRect(370, 390, 41, 41))
        self.topFaceBtn.setAutoFillBackground(False)
        self.topFaceBtn.setText("")
        self.topFaceBtn.setCheckable(False)
        self.topFaceBtn.setFlat(True)
        self.topFaceBtn.setObjectName("topFaceBtn")
        self.backFaceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backFaceBtn.setGeometry(QtCore.QRect(370, 440, 41, 41))
        self.backFaceBtn.setAutoFillBackground(False)
        self.backFaceBtn.setText("")
        self.backFaceBtn.setCheckable(False)
        self.backFaceBtn.setFlat(True)
        self.backFaceBtn.setObjectName("backFaceBtn")
        self.rightFaceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.rightFaceBtn.setGeometry(QtCore.QRect(420, 440, 41, 41))
        self.rightFaceBtn.setAutoFillBackground(False)
        self.rightFaceBtn.setText("")
        self.rightFaceBtn.setCheckable(False)
        self.rightFaceBtn.setFlat(True)
        self.rightFaceBtn.setObjectName("rightFaceBtn")
        self.leftFaceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.leftFaceBtn.setGeometry(QtCore.QRect(320, 440, 41, 41))
        self.leftFaceBtn.setAutoFillBackground(False)
        self.leftFaceBtn.setText("")
        self.leftFaceBtn.setCheckable(False)
        self.leftFaceBtn.setFlat(True)
        self.leftFaceBtn.setObjectName("leftFaceBtn")
        self.frontFaceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.frontFaceBtn.setGeometry(QtCore.QRect(470, 440, 41, 41))
        self.frontFaceBtn.setAutoFillBackground(False)
        self.frontFaceBtn.setText("")
        self.frontFaceBtn.setCheckable(False)
        self.frontFaceBtn.setFlat(True)
        self.frontFaceBtn.setObjectName("frontFaceBtn")
        self.bottomFaceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.bottomFaceBtn.setGeometry(QtCore.QRect(370, 490, 41, 41))
        self.bottomFaceBtn.setAutoFillBackground(False)
        self.bottomFaceBtn.setText("")
        self.bottomFaceBtn.setCheckable(False)
        self.bottomFaceBtn.setFlat(True)
        self.bottomFaceBtn.setObjectName("bottomFaceBtn")
        self.directionalCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.directionalCheck.setGeometry(QtCore.QRect(20, 440, 81, 17))
        self.directionalCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.directionalCheck.setObjectName("directionalCheck")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 410, 71, 16))
        self.label_3.setObjectName("label_3")
        self.placeSound = QtWidgets.QLineEdit(self.centralwidget)
        self.placeSound.setGeometry(QtCore.QRect(100, 410, 151, 20))
        self.placeSound.setObjectName("placeSound")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 180, 47, 13))
        self.label_7.setObjectName("label_7")
        self.author = QtWidgets.QLineEdit(self.centralwidget)
        self.author.setGeometry(QtCore.QRect(80, 180, 121, 20))
        self.author.setObjectName("author")
        self.buttonEditBlock = QtWidgets.QPushButton(self.centralwidget)
        self.buttonEditBlock.setGeometry(QtCore.QRect(796, 250, 75, 23))
        self.buttonEditBlock.setObjectName("buttonEditBlock")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 926, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionImport_from_mrdt = QtWidgets.QAction(MainWindow)
        self.actionImport_from_mrdt.setObjectName("actionImport_from_mrdt")
        self.actiont = QtWidgets.QAction(MainWindow)
        self.actiont.setObjectName("actiont")
        self.actionExport_to_mrdt_2 = QtWidgets.QAction(MainWindow)
        self.actionExport_to_mrdt_2.setObjectName("actionExport_to_mrdt_2")
        self.menuFile.addAction(self.actionImport_from_mrdt)
        self.menuFile.addAction(self.actionExport_to_mrdt_2)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "mDirt - A Datapack Tool for custom blocks"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.blockName.setToolTip(_translate("MainWindow", "<html><head/><body><p>The name the program and the pack recognizes.<br/>Supports lowercase characters &amp; underscores.</p></body></html>"))
        self.blockName.setPlaceholderText(_translate("MainWindow", "ruby_ore"))
        self.vmdPrefix.setToolTip(_translate("MainWindow", "<html><head/><body><p>The prefix for all custom model data in the pack. For instance, if you choose 428, the first block would be 4280001, then 4280002, etc.</p></body></html>"))
        self.vmdPrefix.setPlaceholderText(_translate("MainWindow", "428"))
        self.label_4.setText(_translate("MainWindow", "CMD Prefix:"))
        self.blockDisplayName.setToolTip(_translate("MainWindow", "<html><head/><body><p>The name the block will show in your inventory.</p></body></html>"))
        self.blockDisplayName.setPlaceholderText(_translate("MainWindow", "Ruby Ore"))
        self.label_5.setText(_translate("MainWindow", "Display Name:"))
        self.label_6.setText(_translate("MainWindow", "Base Block:"))
        self.blockBase.setToolTip(_translate("MainWindow", "<html><head/><body><p>The base block. This will determine the mining speed, what kind of tool you</p><p>need to mine it, break/place/walking sounds, and more. Any minecraft block works here.</p></body></html>"))
        self.blockBase.setPlaceholderText(_translate("MainWindow", "minecraft:stone"))
        self.buttonAddBlock.setToolTip(_translate("MainWindow", "<html><head/><body><p>Adds the block to the pack!</p></body></html>"))
        self.buttonAddBlock.setText(_translate("MainWindow", "Add Block"))
        self.blockList.setToolTip(_translate("MainWindow", "<html><head/><body><p>A list of all custom blocks you have created.</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "All Blocks"))
        self.buttonRemoveBlock.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click a block from above, then press Remove to delete it.<br/>This action cannot be undone.</p></body></html>"))
        self.buttonRemoveBlock.setText(_translate("MainWindow", "Remove"))
        self.label_10.setText(_translate("MainWindow", "Name:"))
        self.packName.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Name of the Datapack &amp; Resource Pack.<br/>Supports A-Z, a-z, spaces, _, -, !.</p></body></html>"))
        self.packName.setPlaceholderText(_translate("MainWindow", "The Ruby Pack"))
        self.label_11.setText(_translate("MainWindow", "Namespace:"))
        self.packNamespace.setToolTip(_translate("MainWindow", "<html><head/><body><p>The namespace. Only supports lowercase letters &amp; underscores.</p></body></html>"))
        self.packNamespace.setPlaceholderText(_translate("MainWindow", "ores"))
        self.label_12.setText(_translate("MainWindow", "Description:"))
        self.packDescription.setToolTip(_translate("MainWindow", "The Description! Almost all characters are supported."))
        self.packDescription.setPlaceholderText(_translate("MainWindow", "Adds new ores to Minecraft!"))
        self.label_13.setText(_translate("MainWindow", "Version:"))
        self.packVersion.setToolTip(_translate("MainWindow", "<html><head/><body><p>The version the pack will be made for.</p></body></html>"))
        self.packVersion.setItemText(0, _translate("MainWindow", "1.21.3"))
        self.buttonGeneratePack.setToolTip(_translate("MainWindow", "<html><head/><body><p>Generate the Pack(s)!<br/>Press only when you are done!</p></body></html>"))
        self.buttonGeneratePack.setText(_translate("MainWindow", "Generate Pack"))
        self.label_14.setText(_translate("MainWindow", "mDirt - A Datapack Tool for custom blocks"))
        self.label_15.setText(_translate("MainWindow", "Made by Jupiter Dev & JustJoshinDev 2024"))
        self.blockTextureLabel.setText(_translate("MainWindow", "Texture"))
        self.blockResourceCheckBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Highly Recomended!</span><br/>Whether or not you want to create a resource pack with the datapack.<br/>This is highly reccommended, because it will only work without this</p><p>if you have a resource pack already setup in a specific way.</p></body></html>"))
        self.blockResourceCheckBox.setText(_translate("MainWindow", "Create a Resource Pack?"))
        self.blockModelLabel.setText(_translate("MainWindow", "Model:"))
        self.blockModel.setToolTip(_translate("MainWindow", "<html><head/><body><p>The block model! As of now, you can only create full blocks, but</p><p>slabs &amp; stairs are planned for some point.</p></body></html>"))
        self.blockModel.setItemText(0, _translate("MainWindow", "Block"))
        self.label_2.setText(_translate("MainWindow", "Drop:"))
        self.blockDrop.setToolTip(_translate("MainWindow", "<html><head/><body><p>The item dropped when the block is broken.<br/>When empty, it will drop itself.</p></body></html>"))
        self.blockDrop.setPlaceholderText(_translate("MainWindow", "minecraft:diamond"))
        self.topFaceBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Top face of the block</p></body></html>"))
        self.backFaceBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Back face of the block</p></body></html>"))
        self.rightFaceBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Right face of the block</p></body></html>"))
        self.leftFaceBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Left face of the block</p></body></html>"))
        self.frontFaceBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Front face of the block</p></body></html>"))
        self.bottomFaceBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Bottom face of the block</p></body></html>"))
        self.directionalCheck.setToolTip(_translate("MainWindow", "<html><head/><body><p>Should your block be directional?<br/>When checked, it will be placed like a log.<br/>Otherwise, it will always face up.</p></body></html>"))
        self.directionalCheck.setText(_translate("MainWindow", "Directional?"))
        self.label_3.setText(_translate("MainWindow", "Place Sound:"))
        self.placeSound.setToolTip(_translate("MainWindow", "<html><head/><body><p>The sound your block should play when it is placed.<br/>Currently only supports default minecraft sounds,</p><p>but support for custom sounds is coming soon<span style=\" vertical-align:super;\">TM</span></p></body></html>"))
        self.placeSound.setPlaceholderText(_translate("MainWindow", "minecraft:block.stone.place"))
        self.label_7.setText(_translate("MainWindow", "Author:"))
        self.author.setToolTip(_translate("MainWindow", "<html><head/><body><p>The author of the pack. This is used occasionally in the datapack, and should only be lowercase characters, nothing else.</p></body></html>"))
        self.author.setPlaceholderText(_translate("MainWindow", "jupiterdev"))
        self.buttonEditBlock.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click a block from above, then press Edit to edit the block.</p></body></html>"))
        self.buttonEditBlock.setText(_translate("MainWindow", "Edit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionImport_from_mrdt.setText(_translate("MainWindow", "Import from .mrdt"))
        self.actiont.setText(_translate("MainWindow", "t"))
        self.actionExport_to_mrdt_2.setText(_translate("MainWindow", "Export to .mrdt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
