name: Build and Add EXE to Bin Folder

on:
  push:
    tags:
      - 'v*'  # Triggers when a new tag matching v* is pushed
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.x'  # Choose the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5  # Adjust if you need other dependencies

    - name: Install pyinstaller
      run: pip install pyinstaller  # Install pyinstaller to compile the EXE

    - name: Compile Python code into EXE
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon "lib\mDirt.ico" --add-data "src\ui.py;." --add-data "src\item_models.json;." --add-data "src\item_list.json;." --add-data "src\item_select.py;."  "src\main.py"

    - name: Create bin folder
      run: |
        mkdir -p bin  # Create the bin folder if it doesn't exist

    - name: Move EXE to bin folder
      run: |
        New-Item -ItemType Directory -Force -Path ./bin  # Create the bin folder if it doesn't exist
        Move-Item -Path ./dist/main.exe -Destination ./bin/main.exe  # Move the EXE to the bin folder


    - name: Commit and push EXE to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add bin/main.exe  # Add the EXE file to the staging area
        git commit -m "Add EXE to bin folder"
        git push  # Push the EXE to the repository
